### ISSUE TITLE
Vibration is initially enabled, but preferences screen says it is disabled

### ISSUE THREAD

**Issue by JohnVeness** [netmackan/ATimeTracker#13]
Just after installing the app, or after wiping its data, if you press on a task to start or stop it, the device will vibrate. However, if you look in the preferences, it will say vibration is disabled.

**Comment by fidergo-stephane-gourichon** [comment]
Even enabling then disabling vibration then closing preferences normally, still vibrates.

**Comment by netmackan** [comment]
Both issues should have been fixed now.
