### ISSUE TITLE
Bring back the new edit times dialog.

### ISSUE THREAD

**Issue by erAck** [netmackan/ATimeTracker#135]
Please bring back the new edit times dialog that was pushed back in favour of the old nasty clock dial dialog due to an UX misconception. See issue #124 comment https://github.com/netmackan/ATimeTracker/issues/124#issuecomment-467656254 and following.

**Comment by heinrich5991** [comment]
I disagree about the clock dial version being worse. I can enter times much faster; waiting for a keyboard to pop up and typing the numbers takes more time for me.

**Comment by erAck** [comment]
Try to enter exact minutes, like 15:17 and be lucky if you hit it on the second try already. But this isn't only about entering values, the almost entire clock dial area being sensitive to touch it's too easy to accidentally change clock values while trying to scroll the area.

**Comment by heinrich5991** [comment]
For me, even that second try is faster than letting the keyboard pop up.

Perhaps the clock dial could be made less sensitive to touch instead?

**Comment by erAck** [comment]
.

**Comment by erAck** [comment]
.
