### ISSUE TITLE
14-May-2015 update causes application to crash when editing an ongoing task

### ISSUE THREAD

**Issue by fomur** [netmackan/ATimeTracker#34]
Reproduction steps:

1) Click on a task and start logging time.
2) Long press on task and hit "show times".
3) On the ongoing time (the one with a checkmark and without a finish time), either click or long press and hit "edit time"
4) "Unfortunately TimeTracker stopped" warning comes up and application restarts. 

Luckily it doesn't ruin database. And once the time is stopped, the entry can be edited. But not without stopping it. Until this update I have been using this usage case without any issues.

OS: CyanogenMod 11-20141112-SNAPSHOT-M12-ville
Android Version: 4.4.4
Phone: HTC One S

**Comment by netmackan** [comment]
Confirmed. This is an regression in the latest release. Thank you for the detailed report.

**Comment by fomur** [comment]
Thanks for quickly following up. Looking for a hotfix as soon as you are available :)

Date: Fri, 15 May 2015 14:15:29 -0700

**Comment by netmackan** [comment]
The change is referenced in this ticket. I will create a new release now.

**Comment by fomur** [comment]
Thanks!

Date: Fri, 15 May 2015 14:41:58 -0700

**Comment by Minoru** [comment]
Please excuse me for commenting on a closed issue, but when will the new version become available on F-Droid? I've looked through the Manual and About page, but they don't mention if updates should be submitted manually (by author?) or are picked up from Git automatically.

**Comment by netmackan** [comment]
Version 0.21 is available on f-droid. I think the admins discover the update by the git tag and then it will be available after the next build which I think is run once a day or so but better ask f-droid.
