### ISSUE TITLE
crash on restore

### ISSUE THREAD

**Issue by pille** [netmackan/ATimeTracker#35]
when trying to restore a backup, the app crashes with "Unfortunately, A Time Tracker has stopped."
this happens directly after selecting the menu item.

**Comment by netmackan** [comment]
Confirmed, this happened on my device to.

**Comment by netmackan** [comment]
The only situation I found where the app crashes was if the backup could not be read. This could happen if the backup was never created, the device does not have an SD-card or the file could not be read for any other reasons.
I have added a check for if the file exists before attempting a restoration as well as displaying an error message for any other error.
Please, re-open if the issue remains after this fix.

**Comment by pille** [comment]
could not test until you release it to f-droid.

**Comment by pille** [comment]
to conclude this: does not crash anymore.

**Comment by netmackan** [comment]
Thanks for confirming.
