### ISSUE TITLE
Crashes after stopping any task on Android 6

### ISSUE THREAD

**Issue by emanspeaks** [netmackan/ATimeTracker#42]
Using version 0.21 from F-Droid after upgrading phone to Android 6 crashes any time I try to stop a task. Did not have issue on Android 5.1.1 with same version.

**Comment by rsnel** [comment]
I looked into it and found a workaround.

Set: 'Multiple concurrently running tasks' to 'Tasks can run at the same time' and the problem goes away.

The backtrace for this crash FYI:
> 03-10 20:55:17.484 17514 17514 D AndroidRuntime: Shutting down VM
> 03-10 20:55:17.487 17514 17514 E AndroidRuntime: FATAL EXCEPTION: main
> 03-10 20:55:17.487 17514 17514 E AndroidRuntime: Process: com.markuspage.android.atimetracker, PID: 17514
> 03-10 20:55:17.487 17514 17514 E AndroidRuntime: Theme: themes:{}
> 03-10 20:55:17.487 17514 17514 E AndroidRuntime: java.util.ConcurrentModificationException
> 03-10 20:55:17.487 17514 17514 E AndroidRuntime:        at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
> 03-10 20:55:17.487 17514 17514 E AndroidRuntime:        at com.markuspage.android.atimetracker.Tasks$TaskAdapter$1.hasNext(Tasks.java:955)
> 03-10 20:55:17.487 17514 17514 E AndroidRuntime:        at com.markuspage.android.atimetracker.Tasks.onListItemClick(Tasks.java:1090)
> 03-10 20:55:17.487 17514 17514 E AndroidRuntime:        at android.app.ListActivity$2.onItemClick(ListActivity.java:319)
> 03-10 20:55:17.487 17514 17514 E AndroidRuntime:        at android.widget.AdapterView.performItemClick(AdapterView.java:310)
> 03-10 20:55:17.487 17514 17514 E AndroidRuntime:        at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
> 03-10 20:55:17.487 17514 17514 E AndroidRuntime:        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
> 03-10 20:55:17.487 17514 17514 E AndroidRuntime:        at android.widget.AbsListView$3.run(AbsListView.java:3903)
> 03-10 20:55:17.487 17514 17514 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
> 03-10 20:55:17.487 17514 17514 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
> 03-10 20:55:17.487 17514 17514 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
> 03-10 20:55:17.487 17514 17514 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5456)
> 03-10 20:55:17.487 17514 17514 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
> 03-10 20:55:17.487 17514 17514 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>03-10 20:55:17.487 17514 17514 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by netmackan** [comment]
Could be an issue that the list of tasks is modified while the code is iterating over the list of tasks to stop all previously active ones.

One quick solution could be maybe be to only disable the first active task found as in the 'only one task can run at a time' there shouldn't be any more tasks to close. The exception to this could possibly be if the user switches mode while multiple tasks are running.

I don't have an Android 6 environment set up at the moment to try to reproduce this and try out a solution.

**Comment by opensource21** [comment]
I have the same issue with marshmallow too. I think it would be better to return a list of active tasks. How could we fixed this issue? can you provide a beta version via F-Droid? I want to avoid to setup a complete android sdk just to fix this bug. On the other hand this is a really nasty bug.

**Comment by opensource21** [comment]
As you see I create a pull request which fix the bug.

**Comment by netmackan** [comment]
Will try also Android5 and then create a new release.

**Comment by opensource21** [comment]
Any idea when the version 0.23 will be available on google-play?

**Comment by netmackan** [comment]
Version 0.23 is available on F-Droid since a day or so and I just submitted it to google-play but it might take a few hours before it shows up there.

**Comment by opensource21** [comment]
Thank you. It was a very good example of the strength of open source
software :-)

2016-06-16 14:05 GMT+02:00 Markus <notifications@github.com>:
