### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by mtancoigne** [netmackan/ATimeTracker#58]
Hi!

I'm willing to learn how to dev android apps, and I find your project perfect for this, as it's small enough to get started.

Can you tell me wich IDE/plugins you are using (or any external specific tools) ? the `.gitignore` and `nbandroid` folder makes me think about NetBeans with nbandroid plugin but I may be wrong...

**Comment by netmackan** [comment]
Awesome!

Yes, I am using NetBeans IDE 8.1 with the NBAndroid plugin.

**Comment by mtancoigne** [comment]
Thank you ! 

I hope i'll get to somthing :D
