### ISSUE TITLE
Terminology change; tasks --> activities

### ISSUE THREAD

**Issue by linuxcaffe** [netmackan/ATimeTracker#77]
even the first line of the original docs say "TimeTracker helps you record the amount of time you spend on activities", but then it immediately, incorrectly and persistently calls these activities "tasks".. they're NOT tasks!

So this issue seeks to change all instances of "tasks" to "activities", in the interface and the docs, for accuracy and clarity.

**Comment by netmackan** [comment]
I haven't reflected on this. In the code it is called Task.
Can you shortly give the difference between a task and an activity and why one is more right than the other in this case?

**Comment by linuxcaffe** [comment]
I agree with  the label ;-)

To me, there is a huge difference between the terms "task" and "activity, and as someone who has been using some sort of task-management software for a dogs age, but I haven't (successfully) used time-tracking app. For me, every time the interface says Task, I have to remind myself that in this case, that means Activities, I'm hoping to track both tasks (with taskwarrior) and activities (with ATT) and so I file this issue.

A task is a single thing to be done, and a group of related tasks called is a "project". One couldn't call a single task or a project an "activity", because each one is unique, and when it's done, it's done. 

ATT just.. isn't "task management" software, and that's ok!

An activity is a generalized description of how you use of your time. It can be defined as specifically or as broadly as one likes, and any number of tasks and/or projects could be performed in given "activities", but some activities are completely unrelated to any task, and yet you could still use ATT to track those too..

Of course I realize how disruptive this suggestion would be, Interface changes, docs revisions and shaking right down to the original codebase, but I'm guessing it's not impossible. It's maybe kind of like ripping off a band-aid, it might be painful, but until you do it, it will continue to be wrong :) 

Tell you what, I'll help with docs, and if you decide not to make the change, I won't tease you about it!

**Comment by netmackan** [comment]
Ok, that's clear, thank you. It shouldn't be a big issue fixing the terminoligy.
