### ISSUE TITLE
add Changelog

### ISSUE THREAD

**Issue by sciamano** [netmackan/ATimeTracker#82]
please add a changelog and link it to F-Droid' metadata. That way the users can easily see the difference between the installed version and the proposed update. It's important for people who really care about the software on their phone and what changes from the app to expect. Right now one has to find and examine all the commit messages to get a picture of what is going on...

**Comment by netmackan** [comment]
Hi sciamano,

The changelog can be seen on the releases page: https://github.com/netmackan/ATimeTracker/releases .
Where exactly do you suggest it to be placed and what should the link point to? Do you have an example on how it could look like?

**Comment by sciamano** [comment]
the docs are there https://f-droid.org/manual/html_node/index.html#SEC_Contents
There are fields like Changelog: Donate: Bitcoin: which you can add https://github.com/netmackan/ATimeTracker/releases as Changelog field (e.g. by creating a merge request for https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.markuspage.android.atimetracker.txt) to your metadata, see for example https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.kontalk.txt

**Comment by netmackan** [comment]
Thank you.
Merge request posted: https://gitlab.com/fdroid/fdroiddata/merge_requests/2301

**Comment by netmackan** [comment]
Added in f-droid since long. Closing.
