### ISSUE TITLE
NiceToHave: All menu item direct access 

### ISSUE THREAD

**Issue by ceever** [netmackan/ATimeTracker#94]
Hi there

I do not quite understand, why the user has to push "More..." when there are only currently two item in the menu list.

Why not put all there? Potentially separating by category.

Cheers

**Comment by netmackan** [comment]
Same as #88  ?

**Comment by ceever** [comment]
Indeed. :-)
-------- Original message --------From: Markus <notifications@github.com> Date: 27/10/2018  12:47  (GMT+01:00) To: netmackan/ATimeTracker <ATimeTracker@noreply.github.com> Cc: ceever <ceever@web.de>, Author <author@noreply.github.com> Subject: Re: [netmackan/ATimeTracker] NiceToHave: All menu item direct access 
  (#94) 
Same as #88  ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/netmackan/ATimeTracker","title":"netmackan/ATimeTracker","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/netmackan/ATimeTracker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@netmackan in #94: Same as #88  ?"}],"action":{"name":"View Issue","url":"https://github.com/netmackan/ATimeTracker/issues/94#issuecomment-433610181"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/netmackan/ATimeTracker/issues/94#issuecomment-433610181",
"url": "https://github.com/netmackan/ATimeTracker/issues/94#issuecomment-433610181",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [netmackan/ATimeTracker] NiceToHave: All menu item direct access  (#94)",
"sections": [
{
"text": "",
"activityTitle": "**Markus**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@netmackan",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"netmackan/ATimeTracker\",\n\"issueId\": 94,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"netmackan/ATimeTracker\",\n\"issueId\": 94\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/netmackan/ATimeTracker/issues/94#issuecomment-433610181"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 367727629\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by netmackan** [comment]
#88 is closed.
